{{- if .Values.sensorExporter.enabled -}}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.sensorExporter.service.annotations }}
  annotations:
{{ toYaml .Values.sensorExporter.service.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "prometheus.sensorExporter.labels" . | nindent 4 }}
{{- if .Values.sensorExporter.service.labels }}
{{ toYaml .Values.sensorExporter.service.labels | indent 4 }}
{{- end }}
  name: {{ template "prometheus.sensorExporter.fullname" . }}
spec:
{{- if .Values.sensorExporter.service.clusterIP }}
  clusterIP: {{ .Values.sensorExporter.service.clusterIP }}
{{- end }}
{{- if .Values.sensorExporter.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.sensorExporter.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.sensorExporter.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.sensorExporter.service.loadBalancerIP }}
{{- end }}
{{- if .Values.sensorExporter.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.sensorExporter.service.loadBalancerSourceRanges }}
    - {{ $cidr }}
  {{- end }}
{{- end }}
  ports:
    - name: metrics
      port: {{ .Values.sensorExporter.service.servicePort }}
      protocol: TCP
      targetPort: 9100
  selector:
    {{- include "prometheus.sensorExporter.matchLabels" . | nindent 4 }}
  type: "{{ .Values.sensorExporter.service.type }}"
{{- end -}}
